### ISSUE TITLE
String builder interface?

### ISSUE THREAD

**Issue by alassek** [michaelherold/ksuid-ruby#28]
One thing I am finding that I do _a lot_ of is build a new KSUID and immediately coerce it to a string.

Have you thought about a public interface for building a string directly? Is there any preferable nomenclature for this sort of thing?

**Comment by michaelherold** [comment]
The thing that comes to mind is a simple `KSUID.string` module method with the same signature as `KSUID.new`. As a functional shorthand:

```ruby
module KSUID
  def self.string(...)
    new(...).to_s
  end
end
```

Would that achieve your goal? It would save a few characters of typing and I see the usefulness of it.

**Comment by alassek** [comment]
Yes, this would serve my purposes well. I'll open a PR
