### ISSUE TITLE
activerecord-ksuid available on Rubygems?

### ISSUE THREAD

**Issue by Dahie** [michaelherold/ksuid-ruby#46]
Hi, 

the readme references adding the activerecord-ksuid gem to the Gemfile, but it can't be found on rubygems and looks like it's not released. Is this the case? Is it in a production ready state?

Thanks, 
Daniel

**Comment by michaelherold** [comment]
I released v1.0.0 of `ksuid` and `activerecord-ksuid` today. Cheers!
