### ISSUE TITLE
Write documentation on how to use KSUIDs as a primary key in ORMs

### ISSUE THREAD

**Issue by michaelherold** [michaelherold/ksuid-ruby#6]
The highest impact guide would be using these in ActiveRecord, due to Rails' influence on the Ruby community. But it would also be interesting to see the following:

1. Sequel
2. ROM
3. ~Mongoid - This one is maybe not worth it since MongoDB already has their ObjectIDs.~

On further reflection, I won't write a Mongoid integration without being asked (or preferably helped). I haven't used Mongoid in years and don't think I would do a good job of it. In addition, the aforementioned ability of their ObjectIDs semi obviates the need for KSUIDs in that context.

**Comment by michaelherold** [comment]
Thanks for the feedback! I've been thinking about the problem this week, so I will update to see if I can easily find a way to do this.

**Comment by troex** [comment]
@michaelherold btw do you use it internally or anywhere with PostgreSQL or MySQL? what field type you use for ksuids? binray/char?

thanks for implementing ksuid in ruby!

**Comment by michaelherold** [comment]
I do not currently, but there's a project I've been thinking of that would benefit from it so I might be soon. I'm not sure which I would consider. I think the binary form might be more efficiently indexed over time, but that's just a guess! Apologies for not having more fully-formed ideas yet.

**Comment by michaelherold** [comment]
@phildionne and @troex, what version(s) of Rails are you on? I'm working on an implementation that is 5.2 compatible and am wondering if I need to go farther back than the latest Rails version.

**Comment by troex** [comment]
I'm actually on sinatra + sequel also our PG database is just first in the pipeline ending in Redshift, since redshift doesn't support binary types, I think my only option would be to use CHAR.

I don't think I'll start using ksuid soon but I'll definitely will try that since we have distributed inbound data flows and currently we relay on incremental primary key which is bottleneck.

**Comment by phildionne** [comment]
Awesome! I'm on 5.2

**Comment by michaelherold** [comment]
> I'm actually on sinatra + sequel also our PG database is just first in the pipeline ending in Redshift, since redshift doesn't support binary types, I think my only option would be to use CHAR.

That makes sense. I decided that storing it as a string was probably more usable from a "looking at the data and seeing what you expect" perspective, so the way I implemented it in ActiveRecord was with a string. I'll see what I can figure out from a Sequel perspective!

> Awesome! I'm on 5.2

Check out the [activerecord branch](https://github.com/michaelherold/ksuid-ruby/tree/activerecord) and see what you think of the approach. I was seeing weird behavior when trying to use it as a primary key, but that was before I hammered out all the bugs. I'm testing against 5.0, 5.1, and 5.2 and they all seem to work. :tada:

**Comment by phildionne** [comment]
Great start! Would you mind opening a PR so I can add a few comments?

**Comment by michaelherold** [comment]
Sure! See #7

**Comment by michaelherold** [comment]
@phildionne, I opened #8 for adding support for Sequel. I'm curious what you think?

**Comment by michaelherold** [comment]
I'm going to close this issue in favor of the two open pull requests I have. Please take a look!
